# Generated by Django 2.2.5 on 2019-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(blank=True, max_length=256, null=True)),
                ('cat2', models.CharField(blank=True, max_length=256, null=True)),
                ('cat3', models.CharField(blank=True, max_length=256, null=True)),
                ('cat4', models.CharField(blank=True, max_length=256, null=True)),
                ('cat0', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
                ('district', models.CharField(blank=True, max_length=256, null=True)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('m2_brut', models.CharField(blank=True, max_length=256, null=True)),
                ('m2_net', models.CharField(blank=True, max_length=256, null=True)),
                ('bulundugu_kat', models.CharField(blank=True, max_length=256, null=True)),
                ('kat_sayisi', models.CharField(blank=True, max_length=256, null=True)),
                ('fiyat', models.CharField(blank=True, max_length=256, null=True)),
                ('ilan_aks', models.CharField(blank=True, max_length=256, null=True)),
                ('ilan_fiyat', models.CharField(blank=True, max_length=256, null=True)),
                ('ilan_no', models.CharField(blank=True, max_length=256, null=True)),
                ('ilan_Tarihi', models.CharField(blank=True, max_length=256, null=True)),
                ('Emlak_Tipi', models.CharField(blank=True, max_length=256, null=True)),
                ('area_brut', models.CharField(blank=True, max_length=256, null=True)),
                ('area_net', models.CharField(blank=True, max_length=256, null=True)),
                ('oda_sayisi', models.CharField(blank=True, max_length=256, null=True)),
                ('bina_yasi', models.CharField(blank=True, max_length=256, null=True)),
                ('floor', models.CharField(blank=True, max_length=256, null=True)),
                ('total_floor', models.CharField(blank=True, max_length=256, null=True)),
                ('isitma', models.CharField(blank=True, max_length=256, null=True)),
                ('banyo_sayisi', models.CharField(blank=True, max_length=256, null=True)),
                ('balkon', models.CharField(blank=True, max_length=256, null=True)),
                ('esyali', models.CharField(blank=True, max_length=256, null=True)),
                ('kullanim_durumu', models.CharField(blank=True, max_length=256, null=True)),
                ('site_icerisinde', models.CharField(blank=True, max_length=256, null=True)),
                ('aidat', models.CharField(blank=True, max_length=256, null=True)),
                ('site_adi', models.CharField(blank=True, max_length=256, null=True)),
                ('krediye_uygun', models.CharField(blank=True, max_length=256, null=True)),
                ('kimden', models.CharField(blank=True, max_length=256, null=True)),
                ('takas', models.CharField(blank=True, max_length=256, null=True)),
                ('gecici_numara_servisi', models.CharField(blank=True, max_length=256, null=True)),
                ('site_preference', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
