# Generated by Django 2.2.5 on 2019-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ilan_no',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
