# Generated by Django 2.2.5 on 2019-10-01 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahibinden', '0002_auto_20190928_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='record_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
